# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

openapi: 3.0.1
info:
  title: Cisco Secure Access Policy Rules and Rule Settings APIs
  version: 1.0.1
  description: |-
    Create and manage the access rules and rule settings in the Access policy.
  contact:
    name: Cloud Security Developer Community

servers:
  - url: https://api.sse.cisco.com/{basePath}
    variables:
      basePath:
        default: policies/v2

tags:
  - name: Access Rules
    description: The API endpoints that manage the access rules for the organization.
  - name: Rule Settings and Defaults
    description: The API endpoints that manage the rule settings and defaults on the access rules.
  - name: Secure Access

security:
  - oauthFlow: []

paths:

  '/settings':
    get:
      tags: 
        - Rule Settings and Defaults
        - Secure Access
      summary: Get Rule Defaults and Global Policy Settings
      description: Get the global policy settings and rule defaults for the organization.
      operationId: getPolicySettings
      security:
        - oauthFlow:
            - policies.settings:read
    put:
      tags:
        - Rule Settings and Defaults
        - Secure Access
      summary: Update Rule Defaults and Global Policy Settings
      description: Update the rule defaults and global policy settings.
      operationId: putPolicySettings
      security:
        - oauthFlow:
            - policies.settings:write
  '/settings/{settingName}':
    get:
      tags: 
        - Rule Settings and Defaults
        - Secure Access
      summary: Get Policy Setting
      description: Get the policy setting identified by the setting name.
      operationId: getPolicySetting
      security:
        - oauthFlow:
            - policies.settings:read
    put:
      tags: 
        - Rule Settings and Defaults
        - Secure Access
      summary: Update Policy Setting
      description: Update the policy setting.
      operationId: putPolicySetting
      security:
        - oauthFlow:
            - policies.settings:write
  '/settingTypes':
    get:
      tags: 
        - Rule Settings and Defaults
        - Secure Access
      summary: List Policy Setting Types
      description: List the policy setting types.
      operationId: getPolicySettingTypes
      security:
        - oauthFlow:
            - policies.settings:read
  '/settingTypes/{settingName}':
    get:
      tags: 
        - Rule Settings and Defaults
        - Secure Access
      summary: Get Policy Setting Type
      description: Get the type of the policy setting.
      operationId: getSettingTypesByName
      security:
        - oauthFlow:
            - policies.settings:read
  '/rules':

    get:
      tags: 
        - Access Rules
        - Secure Access
      summary: List Rules
      description: List the rules in the policy for the organization.
      operationId: listRules
      security:
        - oauthFlow:
            - policies.rules:read
    post:
      tags: 
        - Access Rules
        - Secure Access
      summary: Create Rule
      description: Create a rule on the policy for the organization.
      operationId: addRule
      security:
        - oauthFlow:
            - policies.rules:write
    put:
      tags:
        - Access Rules
        - Secure Access
      summary: Enable Rules
      description: Enable or disable the rules on the policy.
      operationId: putRules
      security:
        - oauthFlow:
            - policies.rules:write
  '/rules/{ruleId}':
    get:
      tags: 
        - Access Rules
        - Secure Access
      summary: Get Rule
      description: Get the details about the rule.
      operationId: getRule
      security:
        - oauthFlow:
            - policies.rules:read
    put:
      tags:
        - Access Rules
        - Secure Access
      summary: Update Rule
      description: Update the properties on the rule.
      operationId: putRule
      security:
        - oauthFlow:
            - policies.rules:write
    delete:
      tags: 
        - Access Rules
        - Secure Access
      summary: Delete Rule
      description: Delete a rule on the policy for the organization.
      operationId: deleteRule
      security:
        - oauthFlow:
            - policies.rules:write
  '/geolocations':

    get:
      tags:
        - Access Rules
        - Secure Access
      summary: List GeoLocations
      description: |-
        List the regional information for the continents and countries.
        You can use the country code to create a block on the traffic defined in an internet access rule.
      operationId: getRegionalLocations
      security:
        - oauthFlow:
            - policies.rules:read
components:

  securitySchemes:
    oauthFlow:
      type: oauth2
      description: The client credential flow.
      flows:
        clientCredentials:
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
          scopes:
            policies.settings:write: 'Write policies global rule settings'
            policies.settings:read: 'Read policies global rule settings'
            policies.rules:read: 'Read policies access rules'
            policies.rules:write: 'Write policies access rules'
