# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

openapi: 3.0.1
info:
  title: Cisco Secure Access Private Resources and Resource Groups API
  description: Manage the Private Resources and Resource Groups in the organization.
  version: 1.0.0
  contact:
    name: Cloud Security Developer Community
servers:
  - url: https://api.sse.cisco.com/{basePath}
    variables:
      basePath:
        default: policies/v2

security:
  - oauthFlow: []

tags:
  - name: Resource Groups
    description: The Secure Access Private Resource Groups
  - name: Private Resources
    description: The Secure Access Private Resources
  - name: Secure Access

paths:
  /privateResourceGroups:
    get:
      tags:
      - Resource Groups
      - Secure Access
      summary: List Resource Groups
      description: List the Private Resource Groups for the organization.
      operationId: listResourceGroups
      security:
        - oauthFlow:
          - policies.privateresourcegroups:read
    post:
      tags:
      - Resource Groups
      - Secure Access
      summary: Create Resource Group
      description: |-
        Create a Private Resource Group for the organization.
        You can create a maximum of 1000 Private Resource Groups.
      operationId: addPrivateResourceGroup
      security:
        - oauthFlow:
          - policies.privateresourcegroups:write
  /privateResourceGroups/{id}:
    get:
      tags:
      - Resource Groups
      - Secure Access
      summary: Get Resource Group
      description: Get the details about a Private Resource Group.
      operationId: getPrivateResourceGroup
      security:
        - oauthFlow:
          - policies.privateresourcegroups:read
    put:
      tags:
      - Resource Groups
      - Secure Access
      summary: Update Resource Group
      description: |-
        Update the `name` and `description` properties on the Private Resource Group.
      operationId: putPrivateResourceGroup
      security:
        - oauthFlow:
          - policies.privateresourcegroups:write
    delete:
      tags:
      - Resource Groups
      - Secure Access
      summary: Delete Resource Group
      description: |-
        Delete the Private Resource Group from the organization.
        Before deleting the Private Resource Group, Secure Access removes the Private Resources
        from the Private Resource Group.
      operationId: deletePrivateResourceGroup
      security:
        - oauthFlow:
          - policies.privateresourcegroups:write
  /privateResources:
    get:
      tags:
        - Private Resources
        - Secure Access
      summary: List Private Resources
      description: List the Private Resources for the organization.
      operationId: listPrivateResources
      security:
        - oauthFlow:
          - policies.privateresources:read
    post:
      tags:
      - Private Resources
      - Secure Access
      summary: Create Private Resource
      description: |-
        Create a Private Resource for the organization. You can add at most 1000 Private Resources to an organization.
        When you add a Private Resource enabled for Zero Trust Access, the Zero Trust Access service automatically manages the private applications.
      operationId: addPrivateResource
      security:
        - oauthFlow:
          - policies.privateresources:write
  /privateResources/{id}:
    get:
      tags:
      - Private Resources
      - Secure Access
      summary: Get Private Resource
      description: Get the details about a Private Resource.
      operationId: getPrivateResource
      security:
        - oauthFlow:
          - policies.privateresources:read
    put:
      tags:
      - Private Resources
      - Secure Access
      summary: Update Private Resource
      description: |-
        Update the properties on a Private Resource.
        You can set the following Private Resource properties: `name`, `description`, `resourceAddresses`, `dnsServerId`, `certificateId`,
        `protocol`, `sni`, and `sslVerificationEnabled`.
      operationId: putPrivateResource
      security:
        - oauthFlow:
          - policies.privateresources:write
    delete:
      tags:
      - Private Resources
      - Secure Access
      summary: Delete Private Resource
      description: |-
        Delete a Private Resource. Remove the Private Resource from any Private Resource Groups before deleting the resource.
        If the Private Resource is the only resource in your organization's Private Resource Groups,
        then Secure Access also removes the Private Resource Groups.
      operationId: deletePrivateResource
      security:
        - oauthFlow:
          - policies.privateresources:write
components:

#    400NameError:
#      description: Bad Request
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              error:
#                type: string
#                description: Error message explaining the reason for failure from the list.
#            example:
#              error: 'name is a required field'

#    400ConnectorGroupError:
#      description: Bad Request
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              error:
#                type: string
#                description: Error message explaining the reason for failure.
#                example: The organization ID is a numeric value.
#              requestId:
#                type: string
#                description: The ID of the request.
#                example: 7d318524-d5a4-4fd8-8b29-ad295b2f035b
#              validationErrors:
#                type: object
#                description: The validation error information.
#                properties:
#                  name:
#                    type: string
#                    description: Indicates the problem with `name` property in the payload.
#                    example: The `name` property is a string with at least one character and no more than 50 characters.
#                  location:
#                    type: string
#                    description: Indicates the problem with the `location` property in the payload.
#                    example: The property value is invalid.
#                  environment:
#                    type: string
#                    description: Indicates the problem with `environment` property in the payload.
#                    example: The property value is invalid.
#      headers:
#        Content-Type:
#          $ref: '#/components/headers/Content-Type'
#        Date:
#          $ref: '#/components/headers/Date'

#    400ConnectorAgentError:
#      description: Bad Request
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              error:
#                type: string
#                description: Error message explaining the reason for failure.
#                example: The organization ID is a numeric value.
#              requestId:
#                type: string
#                description: The ID of the request.
#                example: 7d318524-d5a4-4fd8-8b29-ad295b2f035b
#              validationErrors:
#                type: object
#                properties:
#                  enabled:
#                    type: string
#                    description: Indicates the problem with "enabled" property in the payload
#                    example: The property value is invalid.
#                  confirmed:
#                    type: string
#                    description: Indicates the problem with "confirmed" property in the payload
#                    example: The property value is invalid.
#      headers:
#        Content-Type:
#          $ref: '#/components/headers/Content-Type'
#        Date:
#          $ref: '#/components/headers/Date'

    401Error:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message explaining the reason for failure.
              requestId:
                type: string
                description: The ID of the request.
    403Error:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message explaining the reason for failure.
              requestId:
                type: string
                description: The ID of the request.
    404Error:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message explaining the reason for failure.
              requestId:
                type: string
                description: The ID of the request.
#    409Error:
#      description: Conflict
#      # Duplicate Resource Group name
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              error:
#                type: string
#                description: Error message explaining the reason for failure.
#                example: Connector Group name must be unique.
#      headers:
#        Content-Type:
#          $ref: '#/components/headers/Content-Type'
#        Date:
#          $ref: '#/components/headers/Date'

    500Error:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message explaining the reason for failure.
              requestId:
                type: string
                description: The ID of the request.
  securitySchemes:
    oauthFlow:
      type: oauth2
      description: The client credential flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://api.sse.cisco.com/auth/v2/token'
          scopes:
            policies.privateresourcegroups:read: 'Read the Private Resource Groups resources'
            policies.privateresourcegroups:write: 'Write the Private Resource Groups resources'
            policies.privateresources:read: 'Read the Private Resources resources'
            policies.privateresources:write: 'Write the Private Resources resources'
