# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

openapi: 3.0.3
info:
  title: Cisco Secure Access Third-Party Integrations API
  version: 1.0.0
  description: |-
    Create and manage the third-party applications integrated with Secure Access.
    Secure Access integrates with third-party applications, which support either REST APIs or Webhooks.
  contact:
    name: Cloud Security Developer Community

servers:
  - url: https://api.sse.cisco.com/{basePath}
    variables:
      basePath:
        default: admin/v2

security:
  - oauthFlow: []

tags:
  - name: Integrations
    description: Integration management
  - name: Credentials
    description: Credential management
  - name: Integration Types
    description: Integration types
  - name: Secure Access

paths:

  /integrationTypes:
    get:
      summary: List Types of Integrations
      operationId: getIntegrationTypes
      description: List the types of the third-party applications integrated in the organization.
      security:
        - oauthFlow:
            - admin.integrations:read
      tags:
        - Integration Types
        - Secure Access
  /integrations:
    get:
      summary: List Integrations
      operationId: getIntegrations
      description: List the third-party applications integrated in the organization. Filter the collection by `type` and `status`.
      security:
        - oauthFlow:
            - admin.integrations:read
      tags:
        - Integrations
        - Secure Access
    post:
      summary: Create Integration
      operationId: createIntegration
      description: Create a third-party integration in the organization.
      security:
        - oauthFlow:
            - admin.integrations:write
      tags:
        - Integrations
        - Secure Access
  /integrations/{intId}:
    patch:
      summary: Update Integration
      operationId: updateIntegration
      description: Update an integration in the organization.
      security:
        - oauthFlow:
            - admin.integrations:write
      tags:
        - Integrations
        - Secure Access
    get:
      summary: Get Integration
      operationId: getIntegration
      description: Get an integration by ID.
      security:
        - oauthFlow:
            - admin.integrations:read
      tags:
        - Integrations
        - Secure Access
    delete:
      summary: Delete Integration
      operationId: deleteIntegration
      description: Delete an integration in the organization.
      security:
        - oauthFlow:
            - admin.integrations:write
      tags:
        - Integrations
        - Secure Access
  /integrations/{intId}/credentials:
    post:
      summary: Create Credentials for Integration
      operationId: createCredentialsForIntegration
      description: Create the credentials for a third-party application integrated in the organization.
      security:
        - oauthFlow:
            - admin.integrations:write
      tags:
        - Credentials
        - Secure Access
  /integrations/{intId}/credentials/{credId}:
    get:
      summary: Get Credentials for Integration
      operationId: getCredentialsForIntegration
      description: Get the credentials by ID for an integration.
      security:
        - oauthFlow:
            - admin.integrations:read
      tags:
        - Credentials
        - Secure Access
  /integrations/{intId}/credentials/{credId}/value:
    get:
      summary: Get Value of Credentials for Integration
      operationId: getCredentialsforIntegration
      description: Get the value of the credentials for the integration.
      security:
        - oauthFlow:
            - admin.integrations:read
      tags:
        - Credentials
        - Secure Access
components:

  securitySchemes:

    oauthFlow:
      type: oauth2
      description: The client credential flow.
      flows:
        clientCredentials:
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
          scopes:
            admin.integrations:write: 'Update, delete integrations'
            admin.integrations:read: 'Read integrations'
