# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

openapi: 3.0.3
info:
  title: Cisco Secure Access Network Tunnel Groups and Regions API
  description: Manage the Secure Access Network Tunnel Groups.
  version: 1.0.0
  contact:
    name: Cloud Security Developer Community

servers:
  - url: https://api.sse.cisco.com/{basePath}
    variables:
      basePath:
        default: deployments/v2

tags:
  - name: Network Tunnel Groups
    description: Network Tunnel Groups API endpoints
  - name: Network Tunnel Groups Regions
    description: Network Tunnel Groups Regions API endpoints
  - name: Network Tunnel Groups State
    description: Network Tunnel Groups State API endpoints
  - name: Network Tunnel Groups Peer State
    description: Network Tunnel Groups Peer State API endpoints
  - name: Secure Access

security:
  - oauthFlow: []

paths:
  /networktunnelgroups:
    get:
      tags:
      - Network Tunnel Groups
      - Secure Access
      summary: List Network Tunnel Groups
      description: |-
        List the Network Tunnel Groups in the organization.
        If you enable the `includeStatuses` query parameter in your API request,
        the response includes the `tunnelsStatus` field.
        The maximum number of items in a hub's list of tunnel states (`tunnelsStatus`) is 10.
      operationId: listNetworkTunnelGroups
      security:
        - oauthFlow:
            - deployments.networktunnelgroups:read
    post:
      tags:
        - Network Tunnel Groups
        - Secure Access
      summary: Create Network Tunnel Group
      description: Create a Network Tunnel Group in the organization.
      operationId: addNetworkTunnelGroup
      security:
        - oauthFlow:
            - deployments.networktunnelgroups:write
  /networktunnelgroups/{id}:
    get:
      tags:
        - Network Tunnel Groups
        - Secure Access
      summary: Get Network Tunnel Group
      description: Get a Network Tunnel Group in the organization.
      operationId: getNetworkTunnelGroup
      security:
        - oauthFlow:
            - deployments.networktunnelgroups:read
    patch:
      tags:
        - Network Tunnel Groups
        - Secure Access
      summary: Update Network Tunnel Group
      description: Update a Network Tunnel Group in the organization.
      operationId: patchNetworkTunnelGroup
      security:
        - oauthFlow:
            - deployments.networktunnelgroups:write
    delete:
      tags:
        - Network Tunnel Groups
        - Secure Access
      summary: Delete Network Tunnel Group
      description: Delete a Network Tunnel Group in the organization.
      operationId: deleteNetworkTunnelGroup
      security:
        - oauthFlow:
            - deployments.networktunnelgroups:write
  /networktunnelgroups/{id}/state:
    get:
      tags:
      - Network Tunnel Groups State
      - Secure Access
      summary: Get State of Network Tunnel Group
      description: |-
        Get the status information for the Network Tunnel Group in the organization.
        The maximum number of items in a hub's list of tunnel states (`tunnelsStatus`) is 10.
      operationId: getNetworkTunnelGroupState
      security:
        - oauthFlow:
            - deployments.networktunnelgroups:read
  /networktunnelgroups/{id}/peers:
    get:
      tags:
      - Network Tunnel Groups Peer State
      - Secure Access
      summary: Get Tunnel States for Peers
      description: Get the state of all peers (tunnels) within an organization's Network Tunnel Group and Hub.
      operationId: getPeersState
      security:
        - oauthFlow:
            - deployments.networktunnelgroups:read
  /networktunnelgroups/{id}/networktunnelhubs/{hub_id}/peers/{peer_id}/state:
    get:
      tags:
      - Network Tunnel Groups Peer State
      - Secure Access
      summary: Get Tunnel State
      description: Get the state of a peer (tunnel) within an organization's Network Tunnel Group and Hub.
      operationId: getPeerState
      security:
        - oauthFlow:
            - deployments.networktunnelgroups:read
  /networktunnelgroupsstate:
    get:
      tags:
      - Network Tunnel Groups State
      - Secure Access
      summary: List State of Network Tunnel Groups
      description: |-
        Get the state for each Network Tunnel Group in the organization.
        The maximum number of items in a hub's list of tunnel states (`tunnelsStatus`) is 10.
      operationId: getNetworkTunnelGroupBulkState
      security:
        - oauthFlow:
            - deployments.networktunnelgroups:read
  /regions:
    get:
      tags:
        - Network Tunnel Groups Regions
        - Secure Access
      summary: List Regions for Network Tunnel Groups
      description: List the available regions for the Network Tunnel Groups.
      operationId: listNetworkTunnelGroupRegions
      security:
        - oauthFlow:
            - deployments.regions:read
components:

  # =========================================
  # Security Schemes
  # =========================================
  securitySchemes:
    oauthFlow:
      type: oauth2
      description: client credential flow
      flows:
        clientCredentials:
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
          scopes:
            deployments.networktunnelgroups:read: 'Read network tunnel groups deployments'
            deployments.networktunnelgroups:write: 'Write network tunnel groups deployments'
            deployments.regions:read: 'Read regions for network tunnel groups deployments'


  # =========================================
  # Parameters
  # =========================================

  # =========================================
  # Request Bodies
  # =========================================
  # =========================================
  # Responses Components
  # =========================================