# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

openapi: 3.0.1
info:
  title: Cisco Secure Access Resource Connector Groups and Resource Connectors API
  description: |
    Manage the Resource Connector Groups and Resource Connectors in the organization.
  version: 1.0.0
  contact:
    name: Cloud Security Developer Community

servers:
  - url: https://api.sse.cisco.com/{basePath}
    variables:
      basePath:
        default: deployments/v2

security:
  - oauthFlow: []

tags:
  - name: Connector Groups
    description: Manage the Resource Connector Groups.
  - name: Connectors
    description: Manage the Resource Connectors.
  - name: Secure Access

paths:
  /connectorGroups:
    get:
      tags:
      - Connector Groups
      - Secure Access
      summary: List Resource Connector Groups
      description: |-
        List the Resource Connector Groups in the organization.
        If you include `filters` on the request, the response is a subset of the Resource Connector Groups in the organization.
      operationId: listConnectorGroups
      security:
        - oauthFlow:
          - deployments.resourceconnectors:read
    post:
      tags:
      - Connector Groups
      - Secure Access
      summary: Create Resource Connector Group
      description: Create a Resource Connector Group in the organization.
      operationId: createConnectorGroup
      security:
        - oauthFlow:
          - deployments.resourceconnectors:write
  /connectorGroups/{id}:
    get:
      tags:
      - Connector Groups
      - Secure Access
      summary: Get Resource Connector Group
      description: Get the details about a Resource Connector Group.
      operationId: getConnectorGroup
      security:
        - oauthFlow:
          - deployments.resourceconnectors:read
    put:
      tags:
      - Connector Groups
      - Secure Access
      summary: Update Resource Connector Group
      description: Update the `name` and `location` properties on the Resource Connector Group.
      operationId: putConnectorGroup
      security:
        - oauthFlow:
          - deployments.resourceconnectors:write
    patch:
      tags:
      - Connector Groups
      - Secure Access
      summary: Patch Resource Connector Group
      description: |-
        Update the `name` or `location` properties on the Resource Connector Group, or
        refresh the Resource Connector Group's provisioning key.
      operationId: patchConnectorGroup
      security:
        - oauthFlow:
          - deployments.resourceconnectors:write
    delete:
      tags:
      - Connector Groups
      - Secure Access
      summary: Delete Resource Connector Group
      description: Delete the Resouce Connector Group, including the Connectors in the Resource Connector Group.
      operationId: deleteConnectorGroup
      security:
        - oauthFlow:
          - deployments.resourceconnectors:write
  /connectorGroups/counts:
    get:
      tags:
        - Connector Groups
        - Secure Access
      summary: Get Counts Resource Connector Groups States
      description: Get the counts of the state information for the Resource Connector Groups.
      operationId: getConnectorGroupCount
      security:
        - oauthFlow:
          - deployments.resourceconnectors:read
  /connectorAgents:
    get:
      tags:
      - Connectors
      - Secure Access
      summary: List Connectors
      description: |-
        List the Connectors for the Resouce Connector Groups in the organization.
        If you include query filters on the request, the response is a subset of the Connectors in the organization.
      operationId: listConnectors
      security:
        - oauthFlow:
          - deployments.resourceconnectors:read
  /connectorAgents/{id}:
    get:
      tags:
      - Connectors
      - Secure Access
      summary: Get Connector
      description: Get the details about a Connector.
      operationId: getConnector
      security:
        - oauthFlow:
          - deployments.resourceconnectors:read
    patch:
      tags:
      - Connectors
      - Secure Access
      summary: Patch Connector
      description: Update the properties on the Connector.
      operationId: patchConnector
      security:
        - oauthFlow:
          - deployments.resourceconnectors:write
    delete:
      tags:
      - Connectors
      - Secure Access
      summary: Delete Connector
      description: Remove the Connector from the Resource Connector Group in the organization.
      operationId: deleteConnector
      security:
        - oauthFlow:
          - deployments.resourceconnectors:write
  /connectorAgents/counts:
    get:
      tags:
        - Connectors
        - Secure Access
      summary: Get Counts Connectors States
      description: Get the counts of the state information for the Connectors.
      operationId: getConnectorAgentCount
      security:
        - oauthFlow:
          - deployments.resourceconnectors:read
components:

  securitySchemes:
    oauthFlow:
      type: oauth2
      description: Client credential flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://api.sse.cisco.com/auth/v2/token'
          scopes:
            deployments.resourceconnectors:read: 'Read the Resource Connector Group or Connector resources'
            deployments.resourceconnectors:write: 'Write the Resource Connector Group or Connector resources'
