# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

openapi: 3.0.1
info:
  title: Cisco Secure Access Reporting API
  description: |-
    The Reporting API provides the data to generate the Secure Access reports.
  version: 2.0.1
  contact:
    name: Cloud Security Developer Community
servers:
  - url: https://api.sse.cisco.com/{basePath}
    variables:
      basePath:
        default: reports/v2
tags:
  - name: Activity
  - name: Top Identities
  - name: Identity Distribution
  - name: Top Resources
  - name: Top Destinations
  - name: Top Categories
  - name: Top Event Types
  - name: Top DNS Query Types
  - name: Organization Requests by Hour
  - name: Organization Requests by Timerange
  - name: Organization Requests by Hour and Category
  - name: Organization Requests by Timerange and Category
  - name: Deployment Status
  - name: Bandwidth by Hour
  - name: Bandwidth by Timerange
  - name: Top Files
  - name: Total Requests
  - name: Top Threats
  - name: Top Threat Types
  - name: Utility
  - name: Top IPs
  - name: Summary
  - name: Summaries by Category
  - name: Summaries by Destination
  - name: Summaries by Rule
  - name: Remote Access
  - name: Private Resource
  - name: Requests Resource Connector
  - name: Requests Summary Resource Connector Groups
  - name: Resource Connectors
  - name: Rules Activity
  - name: Unique Resources
  - name: Network Tunnels
  - name: Secure Access

security:
  - oauthFlow: []

paths:
  /activity:
    get:
      tags:
        - Activity
        - Secure Access
      summary: Get Activities (All)
      description: |-
        List all activities (dns/proxy/firewall/ip/intrusion/ztna/decryption) within the timeframe.
        **Note:** The IP activity report is not available.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getActivities
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /activity/dns:
    get:
      tags:
        - Activity
        - Secure Access
      summary: Get Activity DNS
      description: |-
        List all DNS entries within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getActivityDns
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /activity/proxy:
    get:
      tags:
        - Activity
        - Secure Access
      summary: Get Activity Proxy
      description: |-
        List all proxy entries within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getActivityProxy
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /activity/firewall:
    get:
      tags:
        - Activity
        - Secure Access
      summary: Get Activity Firewall
      description: |-
        List all firewall activity within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getActivityFirewall
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /activity/intrusion:
    get:
      tags:
        - Activity
        - Secure Access
      summary: Get Activity Intrusion
      description: |-
        List all Intrusion Prevention System (IPS) activity within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getActivityIntrusion
      security:
        - oauthFlow:
          - reports.granularEvents:read
  # deprecated IP Enforcement Layer
  /activity/ip:
    get:
      tags:
        - Activity
        - Secure Access
      summary: Get Activity IP
      description: |-
        (Deprecated) List all IP activity within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getActivityIP
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /activity/amp-retrospective:
    get:
      tags:
        - Activity
        - Secure Access
      summary: Get Activity AMP Retrospective
      description: |-
        List all AMP retrospective activity within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getActivityAmpRetrospective
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /activity/ztna:
    get:
      tags:
        - Activity
        - Secure Access
      summary: Get Activity ZTNA
      description: |-
        List all Zero Trust Network Access (ZTNA) entries within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getActivityZTNA
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /activity/decryption:
    get:
      tags:
        - Activity
        - Secure Access
      summary: Get Activity Decryption
      description: |-
        List all decryption entries within the timeframe.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getActivityDecryption
      security:
        - oauthFlow:
          - reports.granularEvents:read
  /top-identities:
    get:
      tags:
        - Top Identities
        - Secure Access
      summary: Get Top Identities (All)
      description: |-
        List the identities by the number of requests made, sorted in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIdentities
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-identities/{type}:
    get:
      tags:
        - Top Identities
        - Secure Access
      summary: Get Top Identities
      description: |-
        List the identities for the specific traffic type by the number of requests.
        Sort the results in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIdentitiesType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /identity-distribution:
    get:
      tags:
        - Identity Distribution
        - Secure Access
      summary: Get Identity Distribution (All)
      description: |-
        List the number of requests by identity types.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getIdentityDistribution
      security:
        - oauthFlow:
          - reports.aggregations:read
  /identity-distribution/{type}:
    get:
      tags:
        - Identity Distribution
        - Secure Access
      summary: Get Identity Distribution By Type
      description: |-
        List the number of requests by identity for the type of traffic.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getIdentityDistributionType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-resources:
    get:
      tags:
        - Top Resources
        - Secure Access
      summary: Get Top Resources (All)
      description: |-
        List all resources in descending order. Order the collection by the number of requests to get the resources.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getTopResources
      security:
        - oauthFlow:
          - reports.privateResources:read
  /top-resources/{type}:
    get:
      tags:
        - Top Resources
        - Secure Access
      summary: Get Top Resources by Type
      description: |-
        List the resources for the type of activity in descending order.
        Order the collection by the number of requests to get the resources.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getTopResourcesType
      security:
        - oauthFlow:
          - reports.privateResources:read
  /top-destinations:
    get:
      tags:
        - Top Destinations
        - Secure Access
      summary: Get Top Destinations
      description: |-
        List the destinations by the number of requests made to this destination.
        Return the results in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopDestinations
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-destinations/{type}:
    get:
      tags:
        - Top Destinations
        - Secure Access
      summary: Get Top Destinations By Type
      description: |-
        List the destinations by type of destination and the number of requests made
        to this destination. Return the collection in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopDestinationsType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-urls:
    get:
      tags:
        - Top Destinations
        - Secure Access
      summary: Get Top URLs
      description: |-
        List the top number of URLs that are requested for a certain domain.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopUrls
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-categories:
    get:
      tags:
        - Top Categories
        - Secure Access
      summary: Get Top Categories (All)
      description: |-
        List the categories that received the greatest number of requests.
        Order the number of requests in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopCategories
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-categories/{type}:
    get:
      tags:
        - Top Categories
        - Secure Access
      summary: Get Top Categories By Type
      description: |-
        List the categories for the type of traffic that received the greatest number of requests.
        Order the number of requests in descending order.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopCategoriesType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-eventtypes:
    get:
      tags:
        - Top Event Types
        - Secure Access
      summary: Get Top Event Types (All)
      description: |-
        List the top event types by the number of requests made for each type of event.
        Order the number of requests in descending order.
        The valid event types are: `domain_security`, `domain_integration`,
        `url_security`, `url_integration`, `cisco_amp`, and `antivirus`.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopEventTypes
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-dns-query-types:
    get:
      tags:
        - Top DNS Query Types
        - Secure Access
      summary: Get Top DNS Query Types
      operationId: getTopDNSQueryTypes
      description: |-
        List the top types of DNS query.

        **Access Scope:** Reports > Aggregations > Read-Only
      security:
        - oauthFlow:
          - reports.aggregations:read
  /requests-by-hour:
    get:
      tags:
        - Organization Requests by Hour
        - Secure Access
      summary: Get Requests by Hour (All)
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getRequestsByHour
      security:
        - oauthFlow:
          - reports.aggregations:read
  /requests-by-hour/{type}:
    get:
      tags:
        - Organization Requests by Hour
        - Secure Access
      summary: Get Requests by Hour
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getOrganizationRequestsByHour
      security:
        - oauthFlow:
          - reports.aggregations:read
  /requests-by-timerange:
    get:
      tags:
        - Organization Requests by Timerange
        - Secure Access
      summary: Get Requests by Timerange (All)
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getRequestsByTimerange
      security:
        - oauthFlow:
          - reports.aggregations:read
  /requests-by-timerange/{type}:
    get:
      tags:
        - Organization Requests by Timerange
        - Secure Access
      summary: Get Requests by Timerange
      description: |-
        List the activity volume within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getRequestsByTimerangeType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /categories-by-hour:
    get:
      tags:
        - Organization Requests by Hour and Category
        - Secure Access
      summary: Get Requests by Hour and Category (All)
      description: |-
        List the activity volume within the timeframe by type of category.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getRequestsByHourAndCategory
      security:
        - oauthFlow:
          - reports.aggregations:read
  /categories-by-hour/{type}:
    get:
      tags:
        - Organization Requests by Hour and Category
        - Secure Access
      summary: Get Requests by Hour and Category
      description: |-
        List the activity volume for the type of category within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getRequestsByHourAndCategoryAndType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /categories-by-timerange:
    get:
      tags:
        - Organization Requests by Timerange and Category
        - Secure Access
      summary: Get Requests by Timerange and Category (All)
      description: |-
        List the activity volume within the timeframe by category.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getRequestsByTimerangeAndCategory
      security:
        - oauthFlow:
          - reports.aggregations:read
  /categories-by-timerange/{type}:
    get:
      tags:
        - Organization Requests by Timerange and Category
        - Secure Access
      summary: Get Requests by Timerange and Category
      description: |-
        List the activity volume within the timeframe by category.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getRequestsByTimerangeAndCategoryType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /deployment-status:
    get:
      tags:
        - Deployment Status
        - Secure Access
      summary: Get Deployment Status
      description: |-
        List the deployment status within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getDeploymentStatus
      security:
        - oauthFlow:
          - reports.aggregations:read
  /bandwidth-by-hour:
    get:
      tags:
        - Bandwidth by Hour
        - Secure Access
      summary: Get Bandwidth by Hour (All)
      description: |-
        List the bandwidth in bytes within the timeframe. Only returns proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getBandwidthByHour
      security:
        - oauthFlow:
          - reports.aggregations:read
  /bandwidth-by-timerange:
    get:
      tags:
        - Bandwidth by Timerange
        - Secure Access
      summary: Get Bandwidth by Timerange (All)
      description: |-
        List the bandwidth in bytes within the timeframe. Only returns proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getBandwidthByTimerange
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-files:
    get:
      tags:
        - Top Files
        - Secure Access
      summary: Get Top Files (Proxy)
      description: |-
        List the top files within the timeframe. Only returns proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopFilesProxy
      security:
        - oauthFlow:
          - reports.aggregations:read
  /total-requests:
    get:
      tags:
        - Total Requests
        - Secure Access
      summary: Get Total Requests (All)
      description: |-
        Get the count of the total requests.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTotalRequests
      security:
        - oauthFlow:
          - reports.aggregations:read
  /total-requests/{type}:
    get:
      tags:
        - Total Requests
        - Secure Access
      summary: Get Total Requests (By Type)
      description: |-
        Get the count of the total requests for the request type.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTotalRequestsByType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /requests-summary/appconnector-groups:
    get:
      tags:
        - Requests Summary Resource Connector Groups
        - Secure Access
      summary: Get Requests Summary for Resource Connector Groups
      description: |-
        Get the summary of the request counts for the Resource Connector Groups in the organization.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getRequestsSummaryForAppConnectorGroups
      security:
        - oauthFlow:
          - reports.privateResources:read
  /requests-by-appconnector:
    get:
      tags:
        - Requests Resource Connector
        - Secure Access
      summary: Get Total Requests by Resource Connector
      description: |-
        Get the count of the total requests for each Resource Connector.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getTotalRequestsForAppConnector
      security:
        - oauthFlow:
          - reports.privateResources:read
  /requests-by-appconnector-group:
    get:
      tags:
        - Requests Resource Connector
        - Secure Access
      summary: Get Total Requests by Resource Connector Group
      description: |-
        Get the count of the total requests for the Resource Connector Group.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getTotalRequestsForAppConnectorGroup
      security:
        - oauthFlow:
          - reports.privateResources:read
  /top-threats:
    get:
      tags:
        - Top Threats
        - Secure Access
      summary: Get Top Threats (All)
      description: |-
        Get the top threats within the timeframe. Returns both DNS and proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreats
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-threats/{type}:
    get:
      tags:
        - Top Threats
        - Secure Access
      summary: Get Top Threats (By Type)
      description: |-
        Get the top threats within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreatsByType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-threat-types:
    get:
      tags:
        - Top Threat Types
        - Secure Access
      summary: Get Top Threat Types (All)
      description: |-
        List the top types of threat within the timeframe. Returns both DNS and proxy data.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreatTypes
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-threat-types/{type}:
    get:
      tags:
        - Top Threat Types
        - Secure Access
      summary: Get Top Threat Types By Type
      description: |-
        List the top threat-types within the timeframe.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopThreatTypesByType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /applications:
    get:
      tags:
        - Utility
        - Secure Access
      summary: Get Applications
      operationId: getApplications
      description: |-
        List the applications.

        **Access Scope:** Reports > Utilities > Read-Only
      security:
        - oauthFlow:
          - reports.utilities:read
  /categories:
    get:
      tags:
        - Utility
        - Secure Access
      summary: Get Categories
      description: |-
        List the categories.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getCategories
      security:
        - oauthFlow:
          - reports.utilities:read
  /identities:
    get:
      tags:
        - Utility
        - Secure Access
      summary: Get Identities
      operationId: getIdentities
      description: |-
        List the identities.

        **Access Scope:** Reports > Utilities > Read-Only
      security:
        - oauthFlow:
          - reports.utilities:read
    post:
      tags:
        - Utility
        - Secure Access
      summary: Get Identities By IDs
      description: |-
        Get the identities information by providing a list of identity IDs in the request body.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: postIdentities
      security:
        - oauthFlow:
          - reports.utilities:read
  /identities/{identityid}:
    get:
      tags:
        - Utility
        - Secure Access
      summary: Get Identity
      description: |-
        Get identity by identity ID.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getIdentity
      security:
        - oauthFlow:
          - reports.utilities:read
  /threat-types:
    get:
      tags:
        - Utility
        - Secure Access
      summary: Get Threat Types
      description: |-
        List the threat types.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatTypes
      security:
        - oauthFlow:
          - reports.utilities:read
  /threat-types/{threattypeid}:
    get:
      tags:
        - Utility
        - Secure Access
      summary: Get Threat Type By Threat ID
      description: |-
        List the threat types by threat ID.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatType
      security:
        - oauthFlow:
          - reports.utilities:read
  /threat-names:
    get:
      tags:
        - Utility
        - Secure Access
      summary: Get Threat Names
      description: |-
        List the threat names.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatNames
      security:
        - oauthFlow:
          - reports.utilities:read
  /threat-names/{threatnameid}:
    get:
      tags:
        - Utility
        - Secure Access
      summary: Get Threat Name By Threat ID
      description: |-
        Get the threat name by threat ID.

        **Access Scope:** Reports > Utilities > Read-Only
      operationId: getThreatName
      security:
        - oauthFlow:
          - reports.utilities:read
  /top-ips:
    get:
      tags:
        - Top IPs
        - Secure Access
      summary: Get Top IPs
      description: |-
        List the top IP addresses.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIps
      security:
        - oauthFlow:
          - reports.aggregations:read
  /top-ips/internal:
    get:
      tags:
        - Top IPs
        - Secure Access
      summary: Get Top IPs Internal
      description: |-
        List the top internal IP addresses.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getTopIpsInternal
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summary:
    get:
      tags:
        - Summary
        - Secure Access
      summary: Get Summary (All)
      description: |-
        Get the summary report.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummary
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summary/{type}:
    get:
      tags:
        - Summary
        - Secure Access
      summary: Get Summary By Type
      description: |-
        Get the summary of requests by the traffic type.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummaryByType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-category:
    get:
      tags:
        - Summaries by Category
        - Secure Access
      summary: Get Summaries by Category (All)
      description: |-
        List the summaries of requests by category.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByCategory
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-category/{type}:
    get:
      tags:
        - Summaries by Category
        - Secure Access
      summary: Get Summaries by Category For Type
      description: |-
        List the summaries by category for the type of request.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByCategoryType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-destination:
    get:
      tags:
        - Summaries by Destination
        - Secure Access
      summary: Get Summaries by Destination (All)
      description: |-
        List the summaries by destination.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByDestination
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-destination/{type}:
    get:
      tags:
        - Summaries by Destination
        - Secure Access
      summary: Get Summaries by Destination For Type
      description: |-
        List the summaries by destination for the type of traffic.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getSummariesByDestinationType
      security:
        - oauthFlow:
          - reports.aggregations:read
  /summaries-by-rule/firewall-hitcount:
    get:
      tags:
        - Summaries by Rule
        - Secure Access
      summary: Get Summaries Rule Firewall Hit Count
      description: |-
        List the summaries by rule for the policy rule firewall hit count.

        **Access Scope:** Reports > Summaries by rule > Read-Only
      operationId: getSummariesByRuleFirewallHitcount
      security:
        - oauthFlow:
          - reports.summariesByRule:read
  /summaries-by-rule/hitcount:
    get:
      tags:
        - Summaries by Rule
        - Secure Access
      summary: Get Summaries Rule Hit Count
      description: |-
        List the summaries by rule for the policy rule hit count.

        **Access Scope:** Reports > Summaries by rule > Read-Only
      operationId: getSummariesByRuleHitcount
      security:
        - oauthFlow:
          - reports.summariesByRule:read
  /summaries-by-rule/intrusion:
    get:
      tags:
        - Summaries by Rule
        - Secure Access
      summary: Get Summaries Rule Intrusion
      description: |-
        List the summaries by rule for the intrusion type.

        **Access Scope:** Reports > Summaries by rule > Read-Only
      operationId: getSummariesByRuleIntrusion
      security:
        - oauthFlow:
          - reports.summariesByRule:read
  /remote-access-events:
    get:
      tags:
        - Remote Access
        - Secure Access
      summary: Get Remote Access Events
      description: |-
        List the events logged by remote access VPN.

        **Access Scope:** Reports > Aggregations > Read-Only
      operationId: getRemoteAccessEvents
      security:
        - oauthFlow:
          - reports.aggregations:read
  /private-resources/detailed-stats-timerange:
    get:
      tags:
        - Private Resource
        - Secure Access
      summary: Get Private Resource Access Statistics
      description: |-
        Get the detailed access statistics for a private resource, including total hits count and success or blocked count in a series of time ranges.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getPrivateResourceDetailedStatsTimerange
      security:
        - oauthFlow:
          - reports.privateResources:read
  /private-resources/detailed-stats-identities:
    get:
      tags:
        - Private Resource
        - Secure Access
      summary: Get Private Resource Identities Access Statistics
      description: |-
        Get detailed identity access statistics for a private resource, including a list of identities, total hits count,
        and success or blocked count.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getPrivateResourceDetailedStatsIdentities
      security:
        - oauthFlow:
          - reports.privateResources:read
  /private-resources/summary-stats:
    get:
      tags:
        - Private Resource
        - Secure Access
      summary: Get Private Resource Summary Access Statistics
      description: |-
        Get summary statistics of the hits count, the number of identities that accessed the resources,
        and the last access time for a list of private resource IDs.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getPrivateResourceStats
      security:
        - oauthFlow:
          - reports.privateResources:read
  /unique-resources:
    get:
      tags:
        - Unique Resources
        - Secure Access
      summary: Get Unique Resources (All)
      description: |-
        Get a count of the number of unique resources.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getUniqueResources
      security:
        - oauthFlow:
          - reports.privateResources:read
  /app-connectors/groups/detailed-stats-timerange:
    get:
      tags:
        - Resource Connectors
        - Secure Access
      summary: Get Detailed Resource Connector Group Statistics
      description: |-
        Get detailed Resource Connector Group statistics for either group IDs (`groupIds`) or CPU Threshold (`cputhreshold`) parameters,
        The response includes the average CPU utilization and timestamp for every group in a series of time ranges.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getDetailedStatsForAppConnectorGroups
      security:
        - oauthFlow:
          - reports.privateResources:read
  /app-connectors/groups/overloaded-count:
    get:
      tags:
        - Resource Connectors
        - Secure Access
      summary: Get Count of Overloaded Groups
      description: |-
        Get the count of the overloaded groups that have a CPU Threshold greater than the CPU Threshold (`cputhreshold`) value.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getOverloadedGroupsCount
      security:
        - oauthFlow:
          - reports.privateResources:read
  /app-connectors/detailed-stats-timerange:
    get:
      tags:
        - Resource Connectors
        - Secure Access
      summary: Get Detailed Resource Connector Statistics
      #in a time range for a list of agentIds
      description: |-
        Get detailed Resource Connector statistics for the connector IDs, includes average CPU utilization, total request,
        group ID, and timestamp for every connector ID.

        **Access Scope:** Reports > Private Resources > Read-Only
      operationId: getDetailedStatsForAppConnector
      security:
        - oauthFlow:
          - reports.privateResources:read
  /rules-activity:
    get:
      tags:
        - Rules Activity
        - Secure Access
      summary: Get the Rules for the Event Activity
      description: |-
        Get details about events related to the organization's rules including verdict and resource.

        **Access Scope:** Reports > Private Resources > Read-Only
      # resource is application, service, file
      operationId: rulesActivity
      security:
        - oauthFlow:
          - reports.privateResources:read
  /networkTunnelLogs:
    get:
      tags:
        - Network Tunnels
        - Secure Access
      summary: Get Network Tunnel Logs
      description: |-
        List the events for the network tunnels deployed in the organization.

        **Access Scope:** Reports > Granular Events > Read-Only
      operationId: getTunnelEvents
      security:
        - oauthFlow:
          - reports.granularEvents:read
components:

  securitySchemes:
    oauthFlow:
      type: oauth2
      description: client credential flow
      flows:
        clientCredentials:
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
          scopes:
            reports.granularEvents:read: 'Read reports granular events'
            reports.utilities:read: 'Read reports utilities'
            reports.aggregations:read: 'Read reports aggregations'
            reports.summariesByRule:read: 'Read reports for the summaries of the rule'
            reports.privateResources:read: 'Read reports for the private resources'
