# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

openapi: 3.0.1
info:
  version: 1.0.1
  title: Cisco Secure Access Network and Service Objects API
  description: Manage the Network and Service Objects in the organization.
  contact:
    name: Cloud Security Developer Community

servers:
  - url:  https://api.sse.cisco.com/{basePath}
    variables:
      basePath:
        default: policies/v2

tags:
  - name: Network Objects
    description: Manage the Network Objects in the organization.
  - name: Network Object Groups
    description: Manage the Network Object Groups in the organization.
  - name: Service Objects
    description: Manage the Service Objects in the organization.
  - name: Service Object Groups
    description: Manage the Service Object Groups in the organization.
  - name: Unified Objects
    description: List the Objects and Object Groups in the organization.
  - name: Secure Access

security:
  - oauthFlow: []

paths:

  '/objects/unifiedNetworkObjects':
    get:
      tags:
        - Unified Objects
        - Secure Access
      summary: List Network Objects and Network Groups
      operationId: listUnifiedNetworkObjects
      description: Get the Network Objects and Network Object Groups in the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjects:read
  '/objects/unifiedServiceObjects':
    get:
      tags:
        - Unified Objects
        - Secure Access
      summary: List Service Objects and Service Groups
      operationId: listUnifiedServiceObjects
      description: Get the Service Objects and Service Object Groups in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:read
  '/objects/networkObjects':
    get:
      tags:
        - Network Objects
        - Secure Access
      summary: List Network Objects
      description: Get the Network Objects in the organization.
      operationId: listNetworkObjects
      security:
        - oauthFlow:
          - policies.objects.networkObjects:read
    post:
      tags:
        - Network Objects
        - Secure Access
      summary: Create Network Object
      description: Create a Network Object in the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjects:write
      operationId: createNetworkObject
  '/objects/networkObjects/upload':
    post:
      tags:
        - Network Objects
        - Secure Access
      summary: Upload Network Objects
      operationId: createUploadNetworkObjects
      description: Upload a CSV file with the properties that are required for creating the Network Objects.
      security:
        - oauthFlow:
          - policies.objects.networkObjects:write
  '/objects/networkObjects/validate':
    post:
      tags:
        - Network Objects
        - Secure Access
      summary: Validate Network Objects
      operationId: createValidateNetworkObjects
      description: >-
        Validate a CSV file that includes the properties for creating the Network Objects.
        The system validates the properties for each Network Object in the file and returns a list of the validation errors.
      security:
        - oauthFlow:
          - policies.objects.networkObjects:write
  '/objects/networkObjects/references':
    get:
      tags:
        - Network Objects
        - Secure Access
      summary: List References for Network Objects
      description: |-
        Get the references for the Network Objects in the organization.
        A reference is an access rule or Network Object Group that includes a Network Object.
      security:
        - oauthFlow:
          - policies.objects.networkObjects:read
      operationId: getReferencesForNetworkObjects
  '/objects/networkObjects/{networkObjectId}':
    get:
      tags: 
        - Network Objects
        - Secure Access
      summary: Get Network Object
      description: Get a Network Object in the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjects:read
      operationId: getNetworkObject
    put:
      tags:
      - Network Objects
      - Secure Access
      summary: Update Network Object
      description: Update a Network Object in the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjects:write
      operationId: updateNetworkObject
    delete:
      tags:
        - Network Objects
        - Secure Access
      summary: Delete Network Object
      description: Delete a Network Object in the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjects:write
      operationId: deleteNetworkObject
  '/objects/networkObjects/{networkObjectId}/references':
    get:
      tags:
        - Network Objects
        - Secure Access
      summary: Get References for Network Object
      description: |-
        Get the references for the Network Object in the organization.
        A reference is an access rule or Network Object Group that includes a Network Object.
      security:
        - oauthFlow:
          - policies.objects.networkObjects:read
      operationId: getReferencesForNetworkObject
  '/objects/networkObjectGroups':
    get:
      tags:
        - Network Object Groups
        - Secure Access
      summary: List Network Object Groups
      description: Get the Network Object Groups for the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjectGroups:read
      operationId: getNetworkObjectGroups
    post:
      tags:
        - Network Object Groups
        - Secure Access
      summary: Create Network Object Group
      description: Create a Network Object Group in the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjectGroups:write
      operationId: createNetworkObjectGroup
  '/objects/networkObjectGroups/references':
    get:
      tags:
        - Network Object Groups
        - Secure Access
      summary: List References for Network Object Groups
      description: |-
        Get the references for the Network Object Groups in the organization.
        A reference is an access rule or other Network Object Group that includes a Network Object Group.
      security:
        - oauthFlow:
          - policies.objects.networkObjectGroups:read
      operationId: getReferencesForNetworkObjectGroups
  '/objects/networkObjectGroups/{networkObjectGroupId}':
    get:
      tags:
        - Network Object Groups
        - Secure Access
      summary: Get Network Object Group
      description: Get a Network Object Group in the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjectGroups:read
      operationId: getNetworkObjectGroup
    put:
      tags:
      - Network Object Groups
      - Secure Access
      summary: Update Network Object Group
      description: Update a Network Object Group in the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjectGroups:write
      operationId: updateNetworkObjectGroup
    delete:
      tags:
        - Network Object Groups
        - Secure Access
      summary: Delete Network Object Group
      description: Delete a Network Object Group in the organization.
      security:
        - oauthFlow:
          - policies.objects.networkObjectGroups:write
      operationId: deleteNetworkObjectGroup
  '/objects/networkObjectGroups/{networkObjectGroupId}/references':
    get:
      tags:
        - Network Object Groups
        - Secure Access
      summary: Get References for Network Object Group
      description: |-
        Get the references for the Network Object Group in the organization.
        A reference is an access rule or other Network Object Group that includes a Network Object Group.
      security:
        - oauthFlow:
          - policies.objects.networkObjectGroups:read
      operationId: getReferencesForNetworkObjectGroup
  '/objects/serviceObjects':
    get:
      tags:
        - Service Objects
        - Secure Access
      summary: List Service Objects
      description: Get the Service Objects in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:read
      operationId: getServiceObjects
    post:
      tags:
        - Service Objects
        - Secure Access
      summary: Create Service Object
      description: Create a Service Object for the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:write
      operationId: createServiceObject
  '/objects/serviceObjects/upload':
    post:
      tags:
        - Service Objects
        - Secure Access
      summary: Upload Service Objects
      operationId: createUploadServiceObjects
      description: Upload a CSV file with the properties that are required for creating the Service Objects.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:write
  '/objects/serviceObjects/validate':
    post:
      tags:
        - Service Objects
        - Secure Access
      summary: Validate Service Objects
      operationId: createValidateServiceObjects
      description: >-
        Validate a CSV file that includes the properties for creating the Service Objects.
        The system validates the properties for each Service Object in the file and returns a list of the validation errors.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:write
  '/objects/serviceObjects/references':
    get:
      tags:
        - Service Objects
        - Secure Access
      summary: List References for Service Objects
      description: |-
        Get the references for the Service Objects in the organization.
        A reference is an access rule or Service Object Group that includes a Service Object.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:read
      operationId: getReferencesForServiceObjects
  '/objects/serviceObjects/{serviceObjectId}':
    get:
      tags:
        - Service Objects
        - Secure Access
      summary: Get Service Object
      description: Get a Service Object in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:read
      operationId: getServiceObject
    put:
      tags:
      - Service Objects
      - Secure Access
      summary: Update Service Object
      description: Update a Service Object in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:write
      operationId: updateServiceObject
    delete:
      tags:
        - Service Objects
        - Secure Access
      summary: Delete Service Object
      description: Delete a Service Object in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:write
      operationId: deleteServiceObject
  '/objects/serviceObjects/{serviceObjectId}/references':
    get:
      tags:
        - Service Objects
        - Secure Access
      summary: Get References for Service Object
      description: |-
        Get the references for a Service Object in the organization.
        A reference is an access rule or Service Object Group that includes a Service Object.
      security:
        - oauthFlow:
          - policies.objects.serviceObjects:read
      operationId: getReferencesForServiceObject
  '/objects/serviceObjectGroups':
    get:
      tags:
        - Service Object Groups
        - Secure Access
      summary: List Service Object Groups
      description: Get the Service Object Groups in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjectGroups:read
      operationId: getServiceObjectGroups
    post:
      tags:
        - Service Object Groups
        - Secure Access
      summary: Create Service Object Group
      description: Create a Service Object Group in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjectGroups:write
      operationId: createServiceObjectGroup
  '/objects/serviceObjectGroups/references':
    get:
      tags:
        - Service Object Groups
        - Secure Access
      summary: List References for Service Object Groups
      description: |-
        Get all references for the Service Object Groups in the organization.
        A reference is an access rule or other Service Object Group that includes a Service Object Group.
      security:
        - oauthFlow:
          - policies.objects.serviceObjectGroups:read
      operationId: getReferencesForServiceObjectGroups
  '/objects/serviceObjectGroups/{serviceObjectGroupId}':
    get:
      tags:
        - Service Object Groups
        - Secure Access
      summary: Get Service Object Group
      description: Get a Service Object Group in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjectGroups:read
      operationId: getServiceObjectGroup
    put:
      tags:
      - Service Object Groups
      - Secure Access
      summary: Update Service Object Group
      description: Update a Service Object Group in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjectGroups:write
      operationId: updateServiceObjectGroup
    delete:
      tags:
        - Service Object Groups
        - Secure Access
      summary: Delete Service Object Group
      description: Delete a Service Object Group in the organization.
      security:
        - oauthFlow:
          - policies.objects.serviceObjectGroups:write
      operationId: deleteServiceObjectGroup
  '/objects/serviceObjectGroups/{serviceObjectGroupId}/references':
    get:
      tags:
        - Service Object Groups
        - Secure Access
      summary: Get References for Service Object Group
      description: |-
        Get the references for a Service Object Group in the organization.
        A reference is an access rule or other Service Object Group that includes a Service Object Group.
      security:
        - oauthFlow:
          - policies.objects.serviceObjectGroups:read
      operationId: getReferencesForServiceObjectGroup
components:

  securitySchemes:
    oauthFlow:
      type: oauth2
      description: Client credential flow.
      flows:
        clientCredentials:
          tokenUrl: 'https://api.sse.cisco.com/auth/v2/token'
          scopes:
            policies.objects.networkObjects:read: 'Read the Network Object resources'
            policies.objects.networkObjectGroups:read: 'Read the Network Object Group resources'
            policies.objects.networkObjects:write: 'Write the Network Object resources'
            policies.objects.networkObjectGroups:write: 'Write the Network Object Group resources'
            policies.objects.serviceObjects:read: 'Read the Service Object resources'
            policies.objects.serviceObjectGroups:read: 'Read the Service Object Groups resources'
            policies.objects.serviceObjects:write: 'Write the Service Object resources'
            policies.objects.serviceObjectGroups:write: 'Write the Service Object Group resources'
